version: "3"
services:
  registration-service:
    container_name: boilerplate-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: boilerplate-service
    ports:
      - 3000:3000
    depends_on:
      - redis_service
      - postgre_service
  postgre_service:
    container_name: postgre_service
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      TZ: Etc/UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis_service:
    container_name: redis_service
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/var/lib/redis/data
volumes:
  pgdata: {}
  redisdata: {}